version: "3.11"

services:
  app:
    image: muistot/testserver:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: test-server
    restart: unless-stopped
    tty: true
    volumes:
      - "./images/:/opt/files/"
      - "./src/muistot:/muistot/muistot:ro"
      - "./config.json:/root/config.json:ro"
    ports:
      - "127.0.0.1:5600:80"
    depends_on:
      - db
      - redis
      - maildev
      - namegen
      - adminer
    profiles:
      - server
  db:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "127.0.0.1:5601:3306"
    volumes:
      - "muistot-db-data:/var/lib/mysql"
      - "./database/schemas:/docker-entrypoint-initdb.d:ro"
    profiles:
      - server
  redis:
    hostname: redis
    image: redis:6-alpine
    restart: unless-stopped
    profiles:
      - server
  maildev:
    image: muistot/maildev:latest
    build:
      context: ./mail
      dockerfile: maildev.Dockerfile
    restart: on-failure
    ports:
      - "127.0.0.1:5603:80"
    profiles:
      - server
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - "127.0.0.1:5602:8080"
    profiles:
      - server
  namegen:
    image: muistot/namegen-dev
    build:
      context: ./namegen
      dockerfile: Dockerfile
      target: server
    ports:
      - "127.0.0.1:5604:3306"
    profiles:
      - server
      - test
  testrunner:
    image: muistot/testrunner:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: test-runner
    restart: "no"
    tty: true
    volumes:
      - "./htmlcov/:/test-runner/htmlcov/"
      - "./config-test.json:/root/config.json:ro"
    depends_on:
      - test-db
      - test-redis
      - namegen
    profiles:
      - test
  test-db:
    image: mariadb:10.6
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - "./database/schemas:/docker-entrypoint-initdb.d:ro"
    profiles:
      - test
  test-redis:
    hostname: redis
    image: redis:6-alpine
    restart: "no"
    profiles:
      - test

volumes:
  muistot-db-data:
    external: true