version: "3"

services:
  app:
    build:
      context: .
      dockerfile: testserver.Dockerfile
    restart: unless-stopped
    #tty: true
    volumes:
      - "./images/:/opt/files/"
      - "./src/muistot:/code/muistot:ro"
      - "./config.json:/root/config.json:ro"
    ports:
      - "127.0.0.1:5600:80"
    depends_on:
      - db
      - maildev
      - session-storage
      - username-generator
      - db-access
  db:
    image: mariadb:10.6
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "127.0.0.1:5601:3306"
    volumes:
      - "muistot-db-data:/var/lib/mysql"
      - "./database/schemas:/docker-entrypoint-initdb.d:ro"
  session-storage:
    image: redis:6-alpine
    restart: on-failure
  username-generator:
    build:
      context: ./namegen
    ports:
      - "127.0.0.1:5604:3306"
  maildev:
    build:
      context: ./email
      dockerfile: maildev.Dockerfile
    restart: on-failure
    ports:
      - "127.0.0.1:5603:80"
  db-access:
    image: adminer
    restart: on-failure
    ports:
      - "127.0.0.1:5602:8080"

volumes:
  muistot-db-data:
    external: true