version: "3"

services:
  app:
    build:
      context: .
      dockerfile: testserver.Dockerfile
    restart: on-failure
    tty: true
    volumes:
      - "muistot-file-data:/opt/files/"
      - "./src/muistoja:/code/muistoja:ro"
      - "./test_docker_config.json:/root/config.json:ro"
    ports:
      - "127.0.0.1:5600:80"
    networks:
      - muistot-compose-net
    depends_on:
      - db
      - maildev
  db:
    image: mariadb:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "127.0.0.1:5601:3306"
    networks:
      - muistot-compose-net
    volumes:
      - "muistot-db-data:/var/lib/mysql"
      - "./database/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro"
  db-access:
    image: adminer
    restart: on-failure
    ports:
      - "127.0.0.1:5602:8080"
    networks:
      - muistot-compose-net
  maildev:
    image: maildev/maildev
    restart: on-failure
    ports:
      - "127.0.0.1:5603:80"

networks:
  muistot-compose-net:

volumes:
  muistot-db-data:
    external: true
  muistot-file-data:
    external: true