version: "3"

services:
  app:
    build:
      context: .
      dockerfile: testserver.Dockerfile
    restart: on-failure
    container_name: muistot-compose-server
    volumes:
      - "muistot-file-data:/opt/files/"
      - "./src/app:/code/app"
      - "./test_docker_config.json:/root/config.json"
    ports:
      - "127.0.0.1:5600:80"
    networks:
      - muistot-compose-net
  db:
    image: mariadb:latest
    restart: on-failure
    container_name: muistot-compose-testdb
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "127.0.0.1:5601:3306"
    networks:
      - muistot-compose-net
    volumes:
      - "muistot-db-data:/var/lib/mysql"
      - "./database/schema.sql:/docker-entrypoint-initdb.d/init.sql"
  db-access:
    image: adminer
    restart: on-failure
    container_name: muistot-compose-dbview
    ports:
      - "127.0.0.1:5602:8080"
    networks:
      - muistot-compose-net

networks:
  muistot-compose-net:

volumes:
  muistot-db-data:
    external: true
  muistot-file-data:
    external: true