version: "3"

services:
  test-runner:
    build:
      context: .
      dockerfile: testrunner.Dockerfile
    restart: "no"
    container_name: muistot-test-runner
    tty: true
    volumes:
      - "./htmlcov/:/test-runner/htmlcov/"
      - "./src/app:/test-runner/src/app/:ro"
      - "./src/setup.py:/test-runner/src/setup.py:ro"
      - "./src/test/:/test-runner/test/:ro"
      - "./test_config.json:/test-runner/test_config.json:ro"
    depends_on:
      - test-db
  test-db:
    image: mariadb:latest
    restart: "no"
    container_name: muistot-compose-testdb
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - "./database/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    logging:
      driver: none