version: "3"

services:
  runner:
    build:
      context: .
      dockerfile: testrunner.Dockerfile
    restart: "no"
    tty: true
    volumes:
      - "./htmlcov/:/test-runner/htmlcov/"
      - "./config.json:/test-runner/config.json:ro"
    depends_on:
      - db
      - maildev
      - mailer
  db:
    image: mariadb:latest
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - "./database/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    logging:
      driver: "none"
  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    restart: "no"
    command: maildev --smtp 25 --web 80 --incoming-user muistoja --incoming-pass test
  mailer:
    build:
      context: .
      dockerfile: mailer.Dockerfile
    restart: on-failure
    volumes:
      - "./email/templates.txt:/opt/templates.txt:ro"
      - "./mailer-config.json:/opt/mailer-config.json:ro"
      - "./src/muistoja/:/code/muistoja/:ro"