version: "3"

services:
  runner:
    build:
      context: .
      dockerfile: testrunner.Dockerfile
    restart: "no"
    tty: true
    volumes:
      - "./htmlcov/:/test-runner/htmlcov/"
    depends_on:
      - db
      - session-storage
      - username-generator
  db:
    image: mariadb:10.6
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - "./database/schemas:/docker-entrypoint-initdb.d:ro"
  session-storage:
    image: redis:6-alpine
    restart: "no"
  username-generator:
    build:
      context: ./namegen