version: "3"

services:
  runner:
    build:
      context: .
      dockerfile: testrunner.Dockerfile
    restart: "no"
    tty: true
    volumes:
      - "./htmlcov/:/test-runner/htmlcov/"
    depends_on:
      - db
      - maildev
      - mailer
      - session-storage
      - username-generator
  db:
    image: mariadb:latest
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - "./database/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    logging:
      driver: "none"
  session-storage:
    image: redis:alpine
    restart: "no"
  username-generator:
    build:
      context: ./namegen
  maildev:
    build:
      context: ./email
      dockerfile: maildev.Dockerfile
    restart: "no"
  mailer:
    build:
      context: ./email
      dockerfile: mailer.Dockerfile
    restart: "no"