version: "3"

services:
  test-runner:
    build:
      context: .
      dockerfile: testrunner.Dockerfile
    restart: "no"
    tty: true
    volumes:
      - "./htmlcov/:/test-runner/htmlcov/"
      - "./test_config.json:/test-runner/test_config.json:ro"
    depends_on:
      - test-db
      - test-maildev
  test-db:
    image: mariadb:latest
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - "./database/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    logging:
      driver: "none"
  test-maildev:
    image: maildev/maildev
    restart: "no"