name: Run Tests

on:
  release:
    types: [ published ]
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build the Namegen Image
        run: docker build -t namegen:latest ./namegen
      - name: Invoke Tests
        run: sh scripts/run_tests.sh
      - uses: codecov/codecov-action@v2
        with:
          files: ./htmlcov/coverage.xml
  deploy:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: sh scripts/deploy-backend.sh

