name: Deploy

on:
  release:
    types: [ published ]
  push:
    branches: [ master ]
  workflow_dispatch:

# Job
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Tests
        run: /bin/bash ./scripts/run_tests.sh
  deploy:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: sh scripts/deploy-backend.sh

