name: Deploy

on:
  release:
    types: [ published ]
  workflow_dispatch:

# Job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: sh scripts/deploy-backend.sh